project:
  type: website
  output-dir: docs

website:
  title: "Brian Leung"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Blog
    right: 
      - href: mailto:kpleung@uw.edu
        icon: envelope
      - href: https://github.com/leungkp
        icon: github

execute:
  freeze: auto      

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    mainfont: Roboto Condensed
    toc: true

editor: visual

