project:
  type: website
  output-dir: docs

website:
  title: "BRIAN LEUNG"
  navbar:
    left:
      - href: index.qmd
        text: About
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

