project:
  type: website
  output-dir: docs

website:
  title: "Brian Leung"
  search: false
  navbar:
    right:
      - href: index.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Blog

execute:
  freeze: auto      

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    mainfont: Roboto Condensed
    toc: true

editor: visual

